# Generated by Django 3.1.2 on 2020-10-31 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_proctor',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
